name: Infra issue template
description: Template for infrastructure centered issues.
title: "[Infra] <title>"
labels: [infra]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Affected Resources
    description: First estimate on what resources need to be added/modified/removed.
    placeholder: |
      i.e.
      - Azure Firewall
      - Resource Group
      - Subnet
  validations:
    required: false
- type: dropdown
  id: Environment
  attributes:
    label: Which environment is to be modified?
    multiple: true
    options:
      - Platform Provisioning
      - Platform Hub
      - Development
      - Staging
      - Production
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false